/* Word pools — English & Spanish */
const WORD_POOLS = {
	en: {
		words: [
			'the','be','to','of','and','a','in','that','have','it',
			'for','not','on','with','he','as','you','do','at','this',
			'but','his','by','from','they','we','say','her','she','or',
			'an','will','my','one','all','would','there','their','what',
			'so','up','out','if','about','who','get','which','go','me',
			'when','make','can','like','time','no','just','him','know',
			'take','people','into','year','your','good','some','could',
			'them','see','other','than','then','now','look','only','come',
			'its','over','think','also','back','after','use','two','how',
			'our','work','first','well','way','even','new','want','because',
			'any','these','give','day','most','us','great','between','need',
			'large','often','hand','high','place','hold','turn','was','said',
			'each','tell','does','set','put','end','another','still','learn',
			'house','point','page','letter','mother','answer','found','study',
			'still','plant','cover','food','sun','four','world','music','water',
		],
		quotes: [
			'The quick brown fox jumps over the lazy dog.',
			'To be or not to be that is the question.',
			'All that glitters is not gold.',
			'A journey of a thousand miles begins with a single step.',
			'In the middle of difficulty lies opportunity.',
			'The only way to do great work is to love what you do.',
			'Life is what happens when you are busy making other plans.',
			'The future belongs to those who believe in the beauty of their dreams.',
			'It does not matter how slowly you go as long as you do not stop.',
			'Success is not final failure is not fatal it is the courage to continue that counts.',
			'The best time to plant a tree was twenty years ago the second best time is now.',
			'Whether you think you can or you think you cannot you are right.',
		],
	},
	es: {
		words: [
			'el','la','de','que','y','a','en','un','ser','se',
			'no','haber','por','con','su','para','como','estar','tener','le',
			'lo','todo','pero','mas','hacer','o','poder','decir','este','ir',
			'otro','ese','si','me','ya','ver','porque','dar','cuando','el',
			'muy','sin','vez','mucho','saber','que','sobre','mi','alguno','mismo',
			'yo','tambien','hasta','año','dos','querer','entre','asi','primero',
			'desde','grande','eso','ni','nos','llegar','pasar','tiempo','ella',
			'ser','uno','bien','poco','deber','entonces','poner','cosa','tanto',
			'hombre','vida','mundo','casa','agua','dia','trabajo','parte','lugar',
			'ciudad','pais','mano','ojo','cabeza','corazon','amigo','familia','niño',
			'madre','padre','hermano','escuela','libro','mesa','puerta','ventana',
			'calle','camino','sol','luna','mar','rio','montaña','arbol','flor',
			'perro','gato','pajaro','comer','beber','dormir','caminar','hablar',
			'escribir','leer','jugar','aprender','pensar','sentir','amar','vivir',
		],
		quotes: [
			'En un lugar de la Mancha de cuyo nombre no quiero acordarme.',
			'La vida es lo que pasa mientras estas ocupado haciendo otros planes.',
			'El que lee mucho y anda mucho ve mucho y sabe mucho.',
			'No hay caminos para la paz la paz es el camino.',
			'La imaginacion es mas importante que el conocimiento.',
			'El unico modo de hacer un gran trabajo es amar lo que haces.',
			'La felicidad no es algo hecho viene de tus propias acciones.',
			'Caminante no hay camino se hace camino al andar.',
			'La educacion es el arma mas poderosa que puedes usar para cambiar el mundo.',
			'El conocimiento habla pero la sabiduria escucha.',
			'Quien no vive para servir no sirve para vivir.',
			'La paciencia es amarga pero su fruto es dulce.',
		],
	},
	numbers: [
		'0','1','2','3','4','5','6','7','8','9',
		'10','11','12','13','14','15','16','17','18','19','20',
		'100','200','500','1000','2024','42','7','3','99','365',
		'25','30','40','50','60','75','80','90',
	],
};
