export const WORD_DATABASE = {
    animals: [
        { word: 'gato', hint: 'Mascota común, felino doméstico' },
        { word: 'perro', hint: 'Mejor amigo del humano' },
        { word: 'elefante', hint: 'Animal más grande de tierra' },
        { word: 'cocodrilo', hint: 'Reptil acuático peligroso' },
        { word: 'jirafa', hint: 'Animal con el cuello largo' },
        { word: 'zebra', hint: 'Equino rayado africano' },
        { word: 'mariposa', hint: 'Insecto con alas coloridas' },
        { word: 'ballena', hint: 'Mamífero marino gigante' },
        { word: 'pingüino', hint: 'Ave no voladora polar' },
        { word: 'aguila', hint: 'Ave de rapiña majestuosa' },
        { word: 'leon', hint: 'Rey de la sabana africana' },
        { word: 'tigre', hint: 'Felino rayado asiático' },
        { word: 'oso', hint: 'Mamífero grande y fuerte' },
        { word: 'mono', hint: 'Primate inteligente' },
        { word: 'pinguino', hint: 'Ave del Antártida' },
        { word: 'delfin', hint: 'Mamífero marino inteligente' },
        { word: 'pez', hint: 'Animal acuático con aletas' },
        { word: 'pajaro', hint: 'Animal con alas y plumas' },
        { word: 'hormiga', hint: 'Insecto trabajador' },
        { word: 'araña', hint: 'Artrópodo tejedor de redes' },
        { word: 'tortuga', hint: 'Reptil con caparazón' },
        { word: 'serpiente', hint: 'Reptil sin extremidades' },
        { word: 'raton', hint: 'Roedor pequeño' },
        { word: 'caballo', hint: 'Animal de carga y montura' },
        { word: 'vaca', hint: 'Animal lechero' },
        { word: 'oveja', hint: 'Animal lanudo' },
        { word: 'cerdo', hint: 'Animal con pezuñas de corral' },
        { word: 'gallina', hint: 'Ave que pone huevos' },
        { word: 'camello', hint: 'Animal del desierto' },
        { word: 'hipopotamo', hint: 'Mamífero acuático gigante' }
    ],
    countries: [
        { word: 'mexico', hint: 'País en América del Norte' },
        { word: 'japon', hint: 'País del sol naciente' },
        { word: 'brasil', hint: 'País más grande de América del Sur' },
        { word: 'españa', hint: 'País europeo con paella' },
        { word: 'italia', hint: 'País con la Torre de Pisa' },
        { word: 'francia', hint: 'País con la Torre Eiffel' },
        { word: 'alemania', hint: 'País europeo cervecero' },
        { word: 'canada', hint: 'País al norte de USA' },
        { word: 'noruega', hint: 'País con auroras boreales' },
        { word: 'australia', hint: 'País con canguros y koalas' },
        { word: 'china', hint: 'País más poblado del mundo' },
        { word: 'india', hint: 'País del taj mahal' },
        { word: 'rusia', hint: 'País más grande del mundo' },
        { word: 'argentina', hint: 'País del tango' },
        { word: 'colombia', hint: 'País con café' },
        { word: 'peru', hint: 'País del Machu Picchu' },
        { word: 'chile', hint: 'País alargado de América del Sur' },
        { word: 'tailandia', hint: 'País del sudeste asiático' },
        { word: 'vietnam', hint: 'País de Asia del Sudeste' },
        { word: 'tailandia', hint: 'País con templos budistas' },
        { word: 'grecia', hint: 'País con Acrópolis' },
        { word: 'portugal', hint: 'País con pasteles de nata' },
        { word: 'suiza', hint: 'País neutral alpino' },
        { word: 'suecia', hint: 'País nórdico' },
        { word: 'dinamarca', hint: 'País escandinavo' },
        { word: 'belgica', hint: 'País productor de chocolate' },
        { word: 'holanda', hint: 'País de molinos y tulipanes' },
        { word: 'austria', hint: 'País de música clásica' },
        { word: 'hungria', hint: 'País de paprika' },
        { word: 'turquia', hint: 'País entre Europa y Asia' }
    ],
    objects: [
        { word: 'computadora', hint: 'Dispositivo electrónico para trabajar' },
        { word: 'telefono', hint: 'Aparato para comunicarse' },
        { word: 'television', hint: 'Pantalla para ver programas' },
        { word: 'bicicleta', hint: 'Vehículo con dos ruedas' },
        { word: 'guitarra', hint: 'Instrumento musical de cuerda' },
        { word: 'piano', hint: 'Instrumento con muchas teclas' },
        { word: 'espejo', hint: 'Refleja tu imagen' },
        { word: 'ventana', hint: 'Abre y cierra luz' },
        { word: 'lampara', hint: 'Objeto que ilumina' },
        { word: 'reloj', hint: 'Muestra la hora' },
        { word: 'libro', hint: 'Objeto con páginas' },
        { word: 'mesa', hint: 'Mueble para comer' },
        { word: 'silla', hint: 'Mueble para sentarse' },
        { word: 'cama', hint: 'Mueble para dormir' },
        { word: 'puerta', hint: 'Entrada a una habitación' },
        { word: 'llave', hint: 'Abre la puerta' },
        { word: 'candado', hint: 'Cierra y asegura' },
        { word: 'collar', hint: 'Adorno para el cuello' },
        { word: 'anillo', hint: 'Adorno para los dedos' },
        { word: 'bolsa', hint: 'Contenedor portátil' },
        { word: 'zapato', hint: 'Calzado para los pies' },
        { word: 'sombrero', hint: 'Se usa en la cabeza' },
        { word: 'reloj', hint: 'Accesorio de muñeca' },
        { word: 'moneda', hint: 'Dinero metálico' },
        { word: 'billete', hint: 'Dinero de papel' },
        { word: 'cuchara', hint: 'Utensilio para comer' },
        { word: 'tenedor', hint: 'Utensilio con púas' },
        { word: 'cuchillo', hint: 'Utensilio afilado' },
        { word: 'plato', hint: 'Recipiente para comer' },
        { word: 'vaso', hint: 'Recipiente para beber' }
    ],
    food: [
        { word: 'pizza', hint: 'Comida italiana redonda' },
        { word: 'hamburguesa', hint: 'Comida rápida con carne' },
        { word: 'tacos', hint: 'Comida mexicana' },
        { word: 'enchiladas', hint: 'Comida mexicana con salsa' },
        { word: 'sushi', hint: 'Comida japonesa' },
        { word: 'arroz', hint: 'Cereal blanco cocido' },
        { word: 'pasta', hint: 'Fideos italianos' },
        { word: 'salmon', hint: 'Pez naranjo' },
        { word: 'pollo', hint: 'Ave comestible' },
        { word: 'carne', hint: 'Proteína animal' },
        { word: 'manzana', hint: 'Fruta roja' },
        { word: 'platano', hint: 'Fruta amarilla tropical' },
        { word: 'naranja', hint: 'Fruta cítrica' },
        { word: 'fresa', hint: 'Fruta roja pequeña' },
        { word: 'chocolate', hint: 'Golosina dulce' },
        { word: 'helado', hint: 'Postre congelado' },
        { word: 'pastel', hint: 'Postre horneado' },
        { word: 'galleta', hint: 'Dulce crujiente' },
        { word: 'pan', hint: 'Alimento hecho de harina' },
        { word: 'queso', hint: 'Producto lácteo' },
        { word: 'leche', hint: 'Bebida blanca' },
        { word: 'agua', hint: 'Bebida transparente' },
        { word: 'jugo', hint: 'Bebida de frutas' },
        { word: 'cafe', hint: 'Bebida caliente' },
        { word: 'te', hint: 'Bebida de infusión' },
        { word: 'refresco', hint: 'Bebida carbonatada' },
        { word: 'sopa', hint: 'Comida líquida' },
        { word: 'caldo', hint: 'Líquido de cocción' },
        { word: 'yogur', hint: 'Lácteo fermentado' },
        { word: 'mantequilla', hint: 'Grasa láctea' }
    ],
    sports: [
        { word: 'futbol', hint: 'Deporte con balón de 11 jugadores' },
        { word: 'basquet', hint: 'Deporte de enceste' },
        { word: 'tenis', hint: 'Deporte con raqueta de 2 jugadores' },
        { word: 'voleibol', hint: 'Deporte con red' },
        { word: 'beisbol', hint: 'Deporte con bate y pelota' },
        { word: 'natacion', hint: 'Deporte en agua' },
        { word: 'atletismo', hint: 'Deporte de carreras y saltos' },
        { word: 'ajedrez', hint: 'Juego de tablero estratégico' },
        { word: 'damas', hint: 'Juego de tablero' },
        { word: 'póquer', hint: 'Juego de cartas' },
        { word: 'boxeo', hint: 'Deporte de puñetazos' },
        { word: 'karate', hint: 'Arte marcial japonés' },
        { word: 'judo', hint: 'Arte marcial de agarre' },
        { word: 'ciclismo', hint: 'Deporte en bicicleta' },
        { word: 'esqui', hint: 'Deporte de nieve' },
        { word: 'snowboard', hint: 'Tabla en la nieve' },
        { word: 'gimnasia', hint: 'Deporte de movimiento flexible' },
        { word: 'golf', hint: 'Deporte con palo y bola' },
        { word: 'bowling', hint: 'Deporte de bolos' },
        { word: 'billar', hint: 'Juego de bolas en mesa' },
        { word: 'patinaje', hint: 'Deporte sobre patines' },
        { word: 'surfing', hint: 'Deporte en el agua' },
        { word: 'buceo', hint: 'Deporte bajo el agua' },
        { word: 'esgrima', hint: 'Deporte de sable' },
        { word: 'tiro', hint: 'Deporte de precisión' },
        { word: 'equitacion', hint: 'Deporte a caballo' },
        { word: 'motos', hint: 'Deporte de motocicletas' },
        { word: 'automovilismo', hint: 'Deporte con autos' },
        { word: 'hockey', hint: 'Deporte de hielo con disco' },
        { word: 'lacrosse', hint: 'Deporte con raqueta nativa' }
    ],
    school: [
        { word: 'matemática', hint: 'Estudio de números' },
        { word: 'química', hint: 'Ciencia de reacciones' },
        { word: 'biología', hint: 'Estudio de la vida' },
        { word: 'física', hint: 'Ciencia del movimiento' },
        { word: 'historia', hint: 'Estudio del pasado' },
        { word: 'geografía', hint: 'Estudio de lugares' },
        { word: 'literatura', hint: 'Estudio de libros' },
        { word: 'español', hint: 'Lengua materna' },
        { word: 'inglés', hint: 'Lengua extranjera' },
        { word: 'francés', hint: 'Otro idioma' },
        { word: 'educacion', hint: 'Aprendizaje formal' },
        { word: 'escuela', hint: 'Lugar de estudio' },
        { word: 'colegio', hint: 'Centro educativo' },
        { word: 'universidad', hint: 'Educación superior' },
        { word: 'profesor', hint: 'Persona que enseña' },
        { word: 'alumno', hint: 'Persona que aprende' },
        { word: 'examen', hint: 'Prueba de conocimiento' },
        { word: 'calificacion', hint: 'Nota de desempeño' },
        { word: 'tarea', hint: 'Trabajo escolar' },
        { word: 'leccion', hint: 'Clase o enseñanza' },
        { word: 'biblioteca', hint: 'Lugar con libros' },
        { word: 'laboratorio', hint: 'Lugar de experimentos' },
        { word: 'pizarra', hint: 'Superficie para escribir' },
        { word: 'puptre', hint: 'Mueble escolar' },
        { word: 'bolsa', hint: 'Para llevar útiles' },
        { word: 'lapiz', hint: 'Instrumento de escritura' },
        { word: 'pluma', hint: 'Bolígrafo' },
        { word: 'cuaderno', hint: 'Libro de notas' },
        { word: 'regla', hint: 'Instrumento de medir' },
        { word: 'compas', hint: 'Instrumento de círculos' }
    ],
    professions: [
        { word: 'doctor', hint: 'Profesional de la salud' },
        { word: 'abogado', hint: 'Experto en leyes' },
        { word: 'ingeniero', hint: 'Constructor de obras' },
        { word: 'arquitecto', hint: 'Diseñador de edificios' },
        { word: 'profesor', hint: 'Educador' },
        { word: 'artista', hint: 'Creador de arte' },
        { word: 'músico', hint: 'Toca instrumentos' },
        { word: 'periodista', hint: 'Reportero de noticias' },
        { word: 'científico', hint: 'Investigador' },
        { word: 'contador', hint: 'Maneja números y finanzas' },
        { word: 'peluquero', hint: 'Corta cabello' },
        { word: 'carpintero', hint: 'Trabaja con madera' },
        { word: 'electricista', hint: 'Experto en electricidad' },
        { word: 'plomero', hint: 'Repara tuberías' },
        { word: 'cocinero', hint: 'Prepara comida' },
        { word: 'mesero', hint: 'Sirve en restaurante' },
        { word: 'vendedor', hint: 'Vende productos' },
        { word: 'policía', hint: 'Oficial de ley y orden' },
        { word: 'bombero', hint: 'Apaga incendios' },
        { word: 'piloto', hint: 'Dirige aviones' },
        { word: 'taxista', hint: 'Conduce taxi' },
        { word: 'camionero', hint: 'Conduce camión' },
        { word: 'jardinero', hint: 'Cuida plantas' },
        { word: 'granjero', hint: 'Cultiva la tierra' },
        { word: 'minero', hint: 'Extrae minerales' },
        { word: 'pescador', hint: 'Captura peces' },
        { word: 'cazador', hint: 'Persigue animales' },
        { word: 'sastre', hint: 'Cose ropa' },
        { word: 'panadero', hint: 'Hace pan' },
        { word: 'carnicero', hint: 'Vende carne' }
    ],
    technology: [
        { word: 'internet', hint: 'Red global de información' },
        { word: 'computadora', hint: 'Máquina de procesamiento' },
        { word: 'programacion', hint: 'Creación de software' },
        { word: 'software', hint: 'Programa de computadora' },
        { word: 'hardware', hint: 'Componentes físicos' },
        { word: 'monitor', hint: 'Pantalla de visualización' },
        { word: 'teclado', hint: 'Dispositivo de entrada' },
        { word: 'raton', hint: 'Periférico de control' },
        { word: 'impresora', hint: 'Dispositivo de salida' },
        { word: 'scanner', hint: 'Digitalizador de documentos' },
        { word: 'modem', hint: 'Conecta a internet' },
        { word: 'router', hint: 'Distribuye señal wifi' },
        { word: 'servidor', hint: 'Computadora que sirve datos' },
        { word: 'correo', hint: 'Mensajería electrónica' },
        { word: 'navegador', hint: 'Accede a internet' },
        { word: 'aplicacion', hint: 'Programa especializado' },
        { word: 'telefono', hint: 'Dispositivo móvil' },
        { word: 'tablet', hint: 'Computadora portátil' },
        { word: 'reloj', hint: 'Dispositivo inteligente' },
        { word: 'camara', hint: 'Captura imágenes' },
        { word: 'video', hint: 'Grabación de movimiento' },
        { word: 'audio', hint: 'Sonido digital' },
        { word: 'archivo', hint: 'Documento digital' },
        { word: 'carpeta', hint: 'Contenedor de archivos' },
        { word: 'contraseña', hint: 'Clave de acceso' },
        { word: 'usuario', hint: 'Cuenta de acceso' },
        { word: 'red', hint: 'Conexión de computadoras' },
        { word: 'datos', hint: 'Información digital' },
        { word: 'virus', hint: 'Malware dañino' },
        { word: 'firewall', hint: 'Sistema de seguridad' }
    ],
    nature: [
        { word: 'lluvia', hint: 'Agua que cae del cielo' },
        { word: 'nieve', hint: 'Agua congelada del cielo' },
        { word: 'granizo', hint: 'Hielo en el cielo' },
        { word: 'tormenta', hint: 'Lluvia violenta' },
        { word: 'rayo', hint: 'Descarga eléctrica atmosférica' },
        { word: 'arcoiris', hint: 'Fenómeno óptico de colores' },
        { word: 'nube', hint: 'Agua vaporizada' },
        { word: 'viento', hint: 'Movimiento del aire' },
        { word: 'huracán', hint: 'Tormenta muy fuerte' },
        { word: 'terremoto', hint: 'Movimiento de tierra' },
        { word: 'volcán', hint: 'Montaña que expulsa lava' },
        { word: 'montaña', hint: 'Elevación de tierra' },
        { word: 'rio', hint: 'Curso de agua' },
        { word: 'lago', hint: 'Cuerpo de agua dulce' },
        { word: 'mar', hint: 'Cuerpo de agua salada' },
        { word: 'ocean', hint: 'Masa de agua enorme' },
        { word: 'playa', hint: 'Orilla arenosa' },
        { word: 'desierto', hint: 'Tierra árida' },
        { word: 'bosque', hint: 'Área con muchos árboles' },
        { word: 'arbol', hint: 'Planta grande' },
        { word: 'flor', hint: 'Planta colorida' },
        { word: 'hierba', hint: 'Planta pequeña' },
        { word: 'pasto', hint: 'Hierba para animales' },
        { word: 'rosa', hint: 'Flor romántica' },
        { word: 'tulipán', hint: 'Flor holandesa' },
        { word: 'girasol', hint: 'Flor amarilla grande' },
        { word: 'lirio', hint: 'Flor elegante' },
        { word: 'sol', hint: 'Estrella central' },
        { word: 'luna', hint: 'Satélite de tierra' },
        { word: 'estrella', hint: 'Punto luminoso nocturno' }
    ],
    entertainment: [
        { word: 'película', hint: 'Cinta de cine' },
        { word: 'serie', hint: 'Episodios de televisión' },
        { word: 'telenovela', hint: 'Drama televisivo' },
        { word: 'teatro', hint: 'Espectáculo en vivo' },
        { word: 'danza', hint: 'Movimiento rítmico' },
        { word: 'concierto', hint: 'Presentación musical' },
        { word: 'opera', hint: 'Drama con música' },
        { word: 'musical', hint: 'Espectáculo con canciones' },
        { word: 'circo', hint: 'Espectáculo acrobático' },
        { word: 'magia', hint: 'Truco ilusionista' },
        { word: 'caricatura', hint: 'Dibujos animados' },
        { word: 'comedia', hint: 'Espectáculo cómico' },
        { word: 'tragedia', hint: 'Obra dramática' },
        { word: 'poesía', hint: 'Arte con versos' },
        { word: 'novela', hint: 'Libro narrativo' },
        { word: 'cuento', hint: 'Narración corta' },
        { word: 'pintura', hint: 'Arte visual con colores' },
        { word: 'escultura', hint: 'Arte tridimensional' },
        { word: 'fotografia', hint: 'Arte de capturar imágenes' },
        { word: 'grabado', hint: 'Técnica artística' },
        { word: 'caricatura', hint: 'Dibujo burlón' },
        { word: 'comic', hint: 'Historietas ilustradas' },
        { word: 'videojuego', hint: 'Entretenimiento digital' },
        { word: 'consola', hint: 'Dispositivo de juegos' },
        { word: 'podcast', hint: 'Programa de audio' },
        { word: 'blogger', hint: 'Creador de contenido web' },
        { word: 'youtuber', hint: 'Creador de videos' },
        { word: 'influencer', hint: 'Persona popular en redes' },
        { word: 'streaming', hint: 'Transmisión en vivo' },
        { word: 'realidadv', hint: 'Tecnología inmersiva' }
    ]
};
